package com.leoschulmann.podpishiplz.controller;

public enum EventType {
    MAIN_PANEL_FULL,
    MAIN_PANEL_EMPTY,
    PAGES_ADDED,
    NO_PAGES_IN_DOCUMENT,
    PAGES_REORDERED,
    OVERLAY_SELECTED,
    OVERLAY_DESELECTED,
    OVERLAY_LOADED_FROM_DISK,
    PAGE_ROTATED,
    LOCALE_CHANGED,
    REFRESH_OVERLAYS_PANEL,
    FILE_MODIFIED,
    DRAG_ENTER_EVENT,
    DRAG_EXIT_EVENT,
    DROP_EVENT,
    FILE_UNMODIFIED
}
